.TH TOGLER 1 "July 2025" "__VERSION__" "User Commands"
.SH NAME
togler \- toggle application visibility using xdotool
.SH SYNOPSIS
.B togler
.I <application-name>
.SH DESCRIPTION
Togler is a minimal utility to toggle focus and minimize visibility of an X11 application window using xdotool. Ideal for productivity workflows.
.SH OPTIONS
.TP
.B \-v, --version
Show version and exit.
.SH EXAMPLES
.B togler firefox
.br
Toggles the Firefox window.
.SH AUTHOR
Written by Caesar (https://github.com/caesar003).

